export const LOGIN_TEST = "LOGIN_TEST";

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_FILTERS = 'ADD_FILTERS';
export const REMOVE_FILTERS = 'REMOVE_FILTERS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';