export const AUTH_LOGIN = "LOGIN";
export const AUTH_LOGOUT = "LOGOUT";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_SET_IP = "AUTH_SET_IP";

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_FILTERS = 'ADD_FILTERS';
export const REMOVE_FILTERS = 'REMOVE_FILTERS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const ADD_COMPARE = 'ADD_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';

export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES';

export const ADD_TO_CART = 'ADD_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCRESE_ITEM_IN_CART = 'INCRESE_ITEM_IN_CART';
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART';

export const CONTENT_RETRIEVE_SUCCESS = 'CONTENT_RETRIEVE_SUCCESS';
export const CONTENT_RETRIEVE_FAIL = 'CONTENT_RETRIEVE_FAIL';
export const CONTENT_RETRIEVE_START = 'CONTENT_RETRIEVE_START';